### ISSUE TITLE
Caching Beatmaps for Map Pools

### ISSUE THREAD

**Issue by saniistamar** [Tx-ID/tixosu-v2#6]
Each round (semifinal, final, etc) is allocated a Map Pool, a collection of beatmaps that could be chosen or banned throughout a match of that round. Beatmaps in Map Pools are distinguished by both a beatmap ID as well as a Mod code (representing some combination of mods). Each combination of beatmap and mod code produces potentially unique difficulty metrics. 

Caching beatmap info is crucial, as the payload is quite large and must be fetched from the osu! API.

The first implementation will cache beatmap info into Redis by a concatenated key of the beatmap ID and the mod code.

**Comment by Tx-ID** [comment]
I don't know how you will approach this:

1. separate beatmap data and beatmap difficulty into two different cache
2. only fetch beatmap difficulty along with beatmap data into one hash

**Comment by saniistamar** [comment]
Ah, yes. I was going to store them nonseparate (meaning some duplicate beatmap data if we need multiple mod configs of the same map). Then move on to the more refined approach which is to cache them separately and retrieve them separately in the data layer (modules Osu and Upstash), then combined before being returned to the service layer (module Beatmap).

After working on it, though, it's not that much easier. Looks like I might as well go straight to the second approach.
